/**
 * @author Utsav Meher <utsavm@xpanxion.co.in>
 */
var ENV = {
  config: {
    "PAGE_ACCESS_TOKEN" : "EAAB7kvQUUAQBAIWpqpzJEwCYYfKLhDUBen27IVkJtHuRR7ZAzJRYA9wZAuliWOoa8ZBghpoJRZByHsI3E4vBkRLEqzUj3RZABGekGZBOX2mChgpCWux1QFrZBuXIeDI84N8cm4406D6ZClLo4kyHzFaOsXFJHdGKZA1InZBydjVlThOAZDZD",
    "GOOGLE_API_KEY" : "AIzaSyCeh3qV7pBxAdWNHNn8edNipJSTwKEFVCE",
    "WIT_TOKEN" : "VB2CYR7WIRY52DV4CIYSSNYYIM6EXL7B"
  }  
};
module.exports = ENV;